### ISSUE TITLE
Publishing service provider results in error

### ISSUE THREAD

**Issue by saschat** [manifoldco/manifold-laravel#20]
As soon as I publish the Manifold service provider in my Laravel 5.7 project via `php artisan vendor:publish` I can no longer run `php artisan serve`. It fails with `array_merge(): Argument #2 is not an array` pointing at https://github.com/manifoldco/manifold-laravel/blob/master/src/Core.php#L100.

**Comment by PLaRoche** [comment]
@saschat I'm trying to recreate on my end to help dig in, to do so I did the following:

```

**Comment by saschat** [comment]
Sorry, I should have provider some code. Here is the example I am using: https://github.com/memcachier/examples-laravel-beanstalk/tree/manifold

I have `MANIFOLD_PROJECT=laravel-memcache` set and the `laravel-memcache` project contains a resource called `memcachier` which is a free MemCachier cache.

When I do `php artisan serve` it does seem to get the credentials from Manifold because it takes a few seconds before it fails.

**Comment by saschat** [comment]
So I tried to create a fresh project as you did and then I also do not get the error. But the values I get from `config('memcachier.MEMCACHIER_SERVERS')` is just empty. Maybe it fails because I am not getting values for my credentials?

I am unfortunately pretty new at using Manifold and also not really a PHP expert so I am not sure how to best approach this.

**Comment by PLaRoche** [comment]
Thank you for digging more, sounds like the bug is around the value coming back is null (i.e you are either failing to get the value back for that key or it legit is empty).  WHich is probably that line.  I'll try and recreate this situation so I can prove my fix.

As to why yours @saschat is coming back empty, did you create an API key that is scoped to give you permission to read that "laravel-memcache" project ?  For reference some [docs](https://docs.manifold.co/docs/api-tokens-51SEpobNg4qoeEggWQeoWa)

**Comment by saschat** [comment]
You are right, I have a `read` token instead of a `read-credentials` token. But with more powerful tokens it only got weirder:
* If I create a token on the Manifold web dashboard and use that I get 
`In Core.php line 148: count(): Parameter must be an array or an object that implements Countable` and the values are still `NULL`.
* If I create a token on the command line with there is no error but the values are still `NULL`.

**Comment by PLaRoche** [comment]
I definitely think there is a bug around  not dealing with null, I'll try and get to solving that asap.  To why you are getting NULL, I think  this comes down to scoping the api key properly and making sure it has access to the keys you are trying to pull.  Thank you for pointing this out.

To debug your situation, I would suggest using that api key locally in CLI to make sure you can indeed see the the resource you are trying to get via the code (just to sanity check).

I would, in the cli:
- log out `manifold logout`
- `MANIFOLD_API_TOKEN=abc manifold export -p laravel-memcache` 

That should show you all the keys you have access to.  If it comes back with stuff, and they match what you are looking for in your code, then I need to dig even more into the code :-)

**Comment by saschat** [comment]
Interesting, so all the API keys I created via the Web dashboard are invalid.
The one I created via the CLI works when doing `manifold export` but `var_dump(config('memcachier.MEMCACHIER_SERVERS'));` is still `NULL`. But at least `php artisan serve` no longer crashes.

**Comment by PLaRoche** [comment]
@saschat thanks for digging more into this.  I think I'll do the following:
- make two new small issues specific to you 1 and 2
- update the readme to indicate what you found in your 3 for now

**Comment by PLaRoche** [comment]
It seems that the ordering of loading the files is done alphabetically.  Have you tried renaming the manifold config file as 00-manifold (as an example).

**Comment by saschat** [comment]
You are right! I missed the little note on top of the post I linked that says that now the order is alphabetical.

I guess a good solution would be to rename the config file to `00-manifold.php` here: https://github.com/manifoldco/manifold-laravel/blob/master/src/manifoldServiceProvider.php#L24

Anyway, I am closing this for now as you created all the related issues you need.

**Comment by PLaRoche** [comment]
TY @saschat , I'll look at getting all this cleaned up, and thank you for all your work in investigating :-)

**Comment by saschat** [comment]
@PLaRoche just a little update: Renaming it by itself will not work because Laravel will then load the Manifold setup into the configuration dictionary with the key `00-manifold` but the Manifold integration expects the values under the `manifold` key.

From what I can tell (feel free to correct me if I am wrong) there is no easy workaround and it would require a rename throughout the whole Manifold integration.
